version: "3.7"
services:
  pgsql1s:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: "${TZ}"
        PASS: "${PASS}"
    image: pgsql1s
    hostname: pgsql1s
    container_name: pgsql1s
    environment:
      - SHEDULE=${SHEDULE}
    networks:
      - host
    volumes:
      - root_pgsql1s:/root
      - database:/database
      - backup:/backup
    healthcheck:
      test: ["CMD", "/bin/bash", "/root/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  host:
    name: host
    external: true

volumes:
   root_pgsql1s:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/_1s/root_pgsql1s/"
   database:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/_1s/database/"
   backup:
      driver: local
      driver_opts:
        type: 'none'
        o: bind
        device: "/_1s/backup/"



