version: "3.7"
services:
  pgsql1s:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: "[TimeZone]"
        PASS: "[PASS]"
        SHEDULE: "[SHEDULE]"
    image: pgsql1s
    container_name: pgsql1s
    ports:
      - "5432:5432"
    volumes:
      - /_1s/root:/root
      - /_1s/bd:/var/lib/pgpro/1c-15/data
      - /_1s/backup:/backup
    restart: always
